### ISSUE TITLE
convertirs token => oauth

### ISSUE THREAD

**Issue by Fr-Dae** [Bot-a-JDR/Bot_planning#40]

**Comment by mortifia** [comment]
ca a besoin de précision car quasiment tout les système utilise une forme de token (mot peut etre mal utiliser)

rfc de [oauth](https://www.rfc-editor.org/rfc/rfc6749#section-1.4) chapitre sur l'acess token 


a besoin d'une raison du besoin de ce changement

**Comment by Fr-Dae** [comment]
deja implémenté
