### ISSUE TITLE
Page Web

### ISSUE THREAD

**Issue by dryasredrock** [Bot-a-JDR/Bot_planning#6]
Ajouter un bouton pour faire un switch dark/light.
Permettre de passer d'un fond sombre à un fond clair.

**Comment by dryasredrock** [comment]
Le choix dark light ne survie pas à la soumission du formulaire
Le tour des champs doivent être tous de la même couleurs ( choix de la couleur la plus sombre pour le contraste)

**Comment by mortifia** [comment]
- https://github.com/UnionRolistes/Old_Bot_Planning/issues/20
